services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: amehana1998
      MYSQL_DATABASE: amehanaDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: amehana1998
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
